#!/usr/bin/env python3
"""Generates engine/i18n_table.inc (native builds) and web/i18n.js (web build) from i18n/strings.txt."""
import json, os

here = os.path.dirname(os.path.abspath(__file__))
rows = []
for line in open(os.path.join(here, 'strings.txt'), encoding='utf-8'):
    line = line.rstrip('\n')
    if not line.strip() or line.startswith('#'):
        continue
    cols = [c.strip() for c in line.split(' || ')]
    assert len(cols) == 5, line
    variants = [cols]
    if cols[0].endswith('[...]'):
        base = [c[:-5] if c.endswith('[...]') else c for c in cols]
        variants = [base, [c + '...' for c in base]]
    for v in variants:
        expanded = [v]
        for tag, names in (('{ALT}', ['Option', 'Ctrl', 'Alt']), ('{CMD}', ['Cmd', 'Alt', 'Ctrl'])):
            if tag in v[0]:
                expanded = [[c.replace(tag, n) for c in e] for e in expanded for n in names]
        rows.extend(expanded)
seen = {}
for r in rows:
    assert r[0] not in seen or seen[r[0]] == r, 'conflicting entries for ' + r[0]
    seen[r[0]] = r
rows = list(seen.values())

def c_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

with open(os.path.join(here, '..', 'engine', 'i18n_table.inc'), 'w', encoding='utf-8') as f:
    f.write('// Generated by i18n/gen.py from i18n/strings.txt - do not edit.\n// {ko, en, ja, it, fr}\n')
    for r in rows:
        f.write('{' + ', '.join(c_str(c) for c in r) + '},\n')
with open(os.path.join(here, '..', 'web', 'i18n.js'), 'w', encoding='utf-8') as f:
    f.write('// Generated by i18n/gen.py from i18n/strings.txt - do not edit.\n// Korean source string -> [en, ja, it, fr]\n')
    f.write('const I18N = ' + json.dumps({r[0]: r[1:] for r in rows}, ensure_ascii=False, indent=0) + ';\n')
print(len(rows), 'entries')
